import { Spacing } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.four,
    flexGrow: 1,
    justifyContent: 'center',
  },
  tasbihCard: {
    padding: Spacing.five,
    borderRadius: 24,
    alignItems: 'center',
    borderWidth: 1,
    gap: Spacing.four,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    marginBottom: 20
  },
  tasbihHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: Spacing.three,
  },
  tasbihIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tasbihTitleContainer: {
    flex: 1,
    gap: 2,
  },
  tasbihTitle: {
    fontSize: 20,
    fontWeight: '800',
  },
  tasbihSubtitle: {
    fontSize: 12,
  },
  targetLabel: {
    fontSize: 12,
    fontWeight: '700',
    alignSelf: 'flex-start',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  presetsRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    alignSelf: 'stretch',
    justifyContent: 'space-between',
  },
  presetChip: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  presetChipText: {
    fontSize: 13,
    fontWeight: '700',
  },
  progressContainer: {
    alignSelf: 'stretch',
    gap: Spacing.one,
  },
  progressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressText: {
    fontSize: 12,
    fontWeight: '600',
  },
  lapsText: {
    fontSize: 13,
    fontWeight: '700',
  },
  counterWrapper: {
    position: 'relative',
    marginVertical: Spacing.four,
    width: 220,
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tasbihRing: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  tasbihNumber: {
    fontSize: 56,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  tasbihTapText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginTop: Spacing.one,
  },
  resetCircle: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  bottomSpacer: {
    height: 10,
    marginBottom: 100,
  },
});
