import { Spacing } from '@/constants/theme';
import { Dimensions, StyleSheet } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
export const COMPASS_SIZE = Math.min(SCREEN_WIDTH - 80, 280);

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContent: {
    paddingHorizontal: Spacing.four,
    alignItems: 'center',
    paddingBottom: 40,
  },
  titleContainer: {
    alignItems: 'center',
    marginTop: Spacing.three,
    marginBottom: Spacing.two,
    gap: 4,
    paddingHorizontal: Spacing.two,
  },
  mainTitle: { fontSize: 24, fontWeight: '800', letterSpacing: -0.5 },
  subtitle: { fontSize: 13, textAlign: 'center', lineHeight: 18 },

  loader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: Spacing.two,
  },
  loaderText: {
    fontSize: 13,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    padding: Spacing.three,
    marginVertical: Spacing.two,
    width: '100%',
  },
  errorText: {
    fontSize: 12,
    color: '#991B1B',
    flex: 1,
  },

  compassWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: Spacing.five,
    paddingBottom: Spacing.two,
    position: 'relative',
  },
  glowRing: {
    position: 'absolute',
    borderWidth: 3,
    borderColor: 'transparent',
    opacity: 0,
    zIndex: -1,
  },
  outerDial: {
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  tickMark: {
    position: 'absolute',
    borderRadius: 1.5,
  },
  dirLabel: {
    position: 'absolute',
    fontSize: 16,
    fontWeight: '800',
  },
  north: { top: 18 },
  east: { right: 22 },
  south: { bottom: 18 },
  west: { left: 22 },
  innerDial: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  northNeedle: {
    position: 'absolute',
    width: 12,
    height: '75%',
    alignItems: 'center',
  },
  northNeedleTop: {
    width: 8,
    height: '50%',
    backgroundColor: '#EF4444',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  northNeedleBottom: {
    width: 4,
    height: '50%',
    backgroundColor: '#94A3B8',
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },

  qiblaNeedle: {
    position: 'absolute',
    width: 24,
    height: '75%',
    alignItems: 'center',
  },
  qiblaNeedleTop: {
    width: 4,
    height: '45%',
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  kaabaIconContainer: {
    position: 'absolute',
    top: -28,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 20,
  },
  qiblaNeedleBottom: {
    width: 4,
    height: '45%',
    backgroundColor: 'transparent',
  },
  centerDot: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 3,
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
  },
  badgeRow: {
    marginTop: Spacing.four,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headingBadge: {
    paddingHorizontal: Spacing.five,
    paddingVertical: Spacing.two,
    borderRadius: 20,
  },
  deviceHeadingLabel: {
    fontSize: 11,
    marginTop: 8,
    fontWeight: '600',
    letterSpacing: 0.2,
  },

  infoCard: {
    width: '100%',
    padding: Spacing.four,
    borderRadius: 20,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  infoCol: {
    flex: 1,
    gap: 4,
  },
  infoIconRow: {
    marginBottom: Spacing.one,
  },
  infoIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  infoDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginHorizontal: Spacing.three,
  },

  buttonRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    width: '100%',
    marginTop: Spacing.four,
  },
  outlineBtn: {
    flex: 1,
    flexDirection: 'row',
    height: 52,
    borderRadius: 26,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.two,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  outlineBtnText: {
    fontSize: 14,
    fontWeight: 'bold',
  },

  sensorWarningCard: {
    flexDirection: 'row',
    padding: Spacing.three,
    alignItems: 'center',
    gap: Spacing.two,
    marginTop: Spacing.four,
    width: '100%',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
  },
  warningText: {
    fontSize: 11,
    lineHeight: 16,
    flex: 1,
  },
});
