import { Spacing } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.three,
    borderBottomWidth: 1,
  },
  backButton: { padding: Spacing.two },
  backButtonPlaceholder: { width: 40 },
  headerTitleContainer: { alignItems: 'center', flex: 1, paddingHorizontal: Spacing.two },
  headerTitle: { fontSize: 16, fontWeight: 'bold' },
  headerSubtitle: { fontSize: 11, marginTop: 2, textAlign: 'center' },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.three,
  },
  loaderText: { fontSize: 14, fontWeight: '500' },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Spacing.five,
    gap: Spacing.three,
  },
  errorText: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  retryButton: {
    paddingHorizontal: Spacing.five,
    paddingVertical: Spacing.two,
    borderRadius: 8,
  },
  retryText: { fontSize: 13, fontWeight: 'bold' },
  listContent: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.two,
  },
  surahHeaderContainer: {
    marginVertical: Spacing.three,
  },
  surahHeaderCard: {
    padding: Spacing.three,
    borderRadius: 14,
    borderWidth: 1,
  },
  surahHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  surahNumberBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  surahNumberText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  surahHeaderTitles: {
    flex: 1,
    gap: 2,
  },
  surahHeaderName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  surahHeaderTranslation: {
    fontSize: 11,
  },
  surahHeaderRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  surahHeaderArabic: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  bismillahCard: {
    marginTop: Spacing.two,
    paddingVertical: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bismillahText: {
    fontFamily: Platform.OS === 'ios' ? 'ui-serif' : 'serif',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#094C3A',
    textAlign: 'center',
  },
  ayahCard: {
    marginVertical: Spacing.two,
    padding: Spacing.four,
    borderRadius: 16,
  },
  ayahHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  numberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ayahNumber: { fontSize: 12, fontWeight: 'bold' },
  ayahHeaderRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  surahNameTag: {
    fontSize: 11,
    fontWeight: '600',
  },
  playButtonCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arabicText: {
    fontSize: 24,
    lineHeight: 44,
    fontWeight: '500',
    textAlign: 'right',
    marginBottom: Spacing.three,
    fontFamily: Platform.OS === 'ios' ? 'ui-serif' : 'serif',
  },
  translationText: { fontSize: 14, lineHeight: 22 },
  playerPanel: {
    position: 'absolute',
    bottom: Spacing.four,
    width: '92%',
    maxWidth: 500,
    alignSelf: 'center',
    padding: Spacing.three,
    borderRadius: 20,
    borderWidth: 1,
    elevation: 10,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    zIndex: 100,
  },
  playerInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  playerTextContainer: { flex: 1, marginRight: Spacing.two },
  playerSurahName: { fontSize: 14, fontWeight: 'bold' },
  playerReciter: { fontSize: 11, marginTop: 2 },
  playerControlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.two,
  },
  utilityBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainPlayBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
});
